// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "CANTalon.h"
#include "CANSpeedController.h"


#include "BallPicker.h"
#include "../RobotMap.h"


BallPicker::BallPicker() : Subsystem("BallPicker") {
	pickerTalon = RobotMap::pickerTalon;

	pickerTalon->SetControlMode(CANSpeedController::kPercentVbus);
	pickerTalon->EnableControl();
	pickerTalon->SetInverted(true);
	pickerTalon->Set(0.0f);

}

void BallPicker::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
	//SetDefaultCommand(new OperatorInputBallPicker());
}

void BallPicker::FuelRiserBeltOn()
{
	pickerTalon->Set(0.5);

}

void BallPicker::FuelRiserBeltOff()
{
	pickerTalon->Set(0.0);
}


