// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "CANTalon.h"
#include "CANSpeedController.h"

#include "Climber.h"
#include "../RobotMap.h"
#include "../Commands/OperatorInputClimber.h"


Climber::Climber() : Subsystem("Climber") {
	climberTalon = RobotMap::climberTalon;

	climberTalon.get()->SetControlMode(CANSpeedController::kPercentVbus);
	climberTalon.get()->EnableControl();
	climberTalon.get()->Set(0.0f);
}

void Climber::InitDefaultCommand() {
	SetDefaultCommand(new OperatorInputClimber());
}

/********* BEGIN METHODS CALLED BY COMMANDS **********/
void Climber::climberEngineAscend(){
	double
		speedOfAscent = RobotMap::CLIMBER_SPEED;

	climberTalon->Set(speedOfAscent);
}

void Climber::climberEngineStop(){
	double
		stop = RobotMap::STOP_SPEED;

	climberTalon->Set(stop);
}
