// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<SpeedController> RobotMap::motorSpeedControllerLeft;
std::shared_ptr<SpeedController> RobotMap::motorSpeedControllerRight;
std::shared_ptr<RobotDrive> RobotMap::motorRobotDrive25;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    //motorSpeedControllerLeft.reset(new Talon(0));
    lw->AddActuator("Motor", "Speed Controller 1", std::static_pointer_cast<Talon>(motorSpeedControllerLeft));
    
    //motorSpeedControllerRight.reset(new Talon(1));
    lw->AddActuator("Motor", "Speed Controller 2", std::static_pointer_cast<Talon>(motorSpeedControllerRight));
    
    motorRobotDrive25.reset(new RobotDrive(motorSpeedControllerLeft, motorSpeedControllerRight));
    
    motorRobotDrive25->SetSafetyEnabled(true);
        motorRobotDrive25->SetExpiration(0.1);
        motorRobotDrive25->SetSensitivity(0.5);
        motorRobotDrive25->SetMaxOutput(1.0);
        motorRobotDrive25->SetInvertedMotor(RobotDrive::kRearLeftMotor, true);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
